-- Additional charge payments: track channel split for advertising payments
ALTER TABLE "AdditionalChargePayment"
ADD COLUMN "bankTransferPaid" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "cashbox1Paid" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "cashbox2Paid" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- Monthly payment aggregate: track channel split by entity
ALTER TABLE "Payment"
ADD COLUMN "rentBankTransferPaid" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "rentCashbox1Paid" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "rentCashbox2Paid" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "utilitiesBankTransferPaid" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "utilitiesCashbox1Paid" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "utilitiesCashbox2Paid" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "advertisingBankTransferPaid" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "advertisingCashbox1Paid" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "advertisingCashbox2Paid" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- Payment transactions: track channel split by entity
ALTER TABLE "PaymentTransaction"
ADD COLUMN "rentBankTransferPaid" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "rentCashbox1Paid" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "rentCashbox2Paid" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "utilitiesBankTransferPaid" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "utilitiesCashbox1Paid" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "utilitiesCashbox2Paid" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "advertisingBankTransferPaid" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "advertisingCashbox1Paid" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "advertisingCashbox2Paid" DOUBLE PRECISION NOT NULL DEFAULT 0;
